dist: trusty
language: node_js

node_js:
  - node

cache: npm

addons:
  sonarcloud:
    organization: erbridge
    token:
      secure: RHERa3Jfz+JVUCoH50znELr+HsClPVoYOAN4GkkMO4jQ1w505sJbquf1XqmwR648wfNWnfkkltNawyPxgPPova5VKm4Ds4vZB3O210/YoF1d46PrLqpxtVz22xKiEwJN27GRnyt9GFvBdC/GlC5zH1Z/6qp3iRY1OzZSf+L5CVkdRcvDd1cba88MvKMeU8Q3KlReO5Ik2s0kVma4bnmdCh0NMaFnxPIxLyNiAMi5xFQ1seCDvJbfEw5KoSXIw0yTTXe14h28Rx/PLsfR3h4Ee7YGpaici3OAdnQCeRzFgBT71Sh4DXVN5OAnjDRjflPHzqD/XdY7b89Mja0XINNt5ihdi8JViQX0rAeQkIQ7FVrx1XC+RR2qb2jIrVR27D0d+YJXUcQo4k0sItON3MzAHIpuTYL+vL8LSduMzwwuOrHLk9DeCaVvomiCKRzKHjCPcQYYqHXF511vKcm8MvQ27knC+MUA3n/x85+xrV7mOSXYuFMu81Jbkzev0CzE260blGid3XWODiY17+U45T1SP7UnvtD43753Wq5yQpG75ezP1jIoENoQ3AhiO4dcNYtrq+4PyeD58aiULFutyKQWG1kQdH2xkcfPryFUvAj3HEiYYwNT1Ae/Ih2AlAOqJTdO8ugYiQGIShRy+VXj37ULW52fi34JxAgIlVt3MEkFTcU=

before_deploy: npm run build

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: Eq8ivyMesg/PF+qEYmrPsz3BR21ciAwMkZ9H8FNBjA99pTHrOk0w7bFyRjydQFATd5HSc9kSnLwLRJv8oMswTuo22Do/uaNW++ajryt2Mw7JwlJdOj8lyJ9Ed961KOwZPDtv62BQrqcDqKFQPZWfegpkf6BrqpzAXlZMdoh0kMFP2YNmlbre781fzg7Pg1jsENq5FLVLfDsTgJJGHvvOEExlIds3+BZjsygGAXXUYsPuFdN0Ic5MJ1cz9PYVS/zABueKv5QTk+6JCIXk0nZjbw5mi36Fs/XN51xHkYfyZAk2WggStulgJtiGOU0Aq84d+zHz725GsBb17J3FwFK0Hgg67+Wr/Q3I53tIvGTd03QRvHQHk6JTviKCvQZNttroEwGvvQK9LpPCyekHgoHbw2/Ep/HvjC5TyGOezGShsQFf0RD1TSrEf9/2b2fsajSQE3gkrqNep7dIY3HJAxVI1GdKCnRtfBZMxW9lcs23AQ64u/jyPUn/Sfls1DnDTUptDB+vzohDZF/IDx4NFsYBQnecQwRsGFF8DKYOpTLIHhY5PwnYmNGPBSlXFOnICG8f3lJKq/Gm7uXJ5lZqmnRoZfRvOoFLZgEWCgkQxRGZLKwz5394kme5tzT09bf6qF8zhi1OJGrERCDWGgGIin4dCZfVXFLDHGppsLKY8+5nWA0=

after_deploy: sonar-scanner
