language: node_js
node_js:
  - node
cache: yarn
before_deploy: yarn build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: Eq8ivyMesg/PF+qEYmrPsz3BR21ciAwMkZ9H8FNBjA99pTHrOk0w7bFyRjydQFATd5HSc9kSnLwLRJv8oMswTuo22Do/uaNW++ajryt2Mw7JwlJdOj8lyJ9Ed961KOwZPDtv62BQrqcDqKFQPZWfegpkf6BrqpzAXlZMdoh0kMFP2YNmlbre781fzg7Pg1jsENq5FLVLfDsTgJJGHvvOEExlIds3+BZjsygGAXXUYsPuFdN0Ic5MJ1cz9PYVS/zABueKv5QTk+6JCIXk0nZjbw5mi36Fs/XN51xHkYfyZAk2WggStulgJtiGOU0Aq84d+zHz725GsBb17J3FwFK0Hgg67+Wr/Q3I53tIvGTd03QRvHQHk6JTviKCvQZNttroEwGvvQK9LpPCyekHgoHbw2/Ep/HvjC5TyGOezGShsQFf0RD1TSrEf9/2b2fsajSQE3gkrqNep7dIY3HJAxVI1GdKCnRtfBZMxW9lcs23AQ64u/jyPUn/Sfls1DnDTUptDB+vzohDZF/IDx4NFsYBQnecQwRsGFF8DKYOpTLIHhY5PwnYmNGPBSlXFOnICG8f3lJKq/Gm7uXJ5lZqmnRoZfRvOoFLZgEWCgkQxRGZLKwz5394kme5tzT09bf6qF8zhi1OJGrERCDWGgGIin4dCZfVXFLDHGppsLKY8+5nWA0=
